export const classes = {
  AppBar: {
    transition: "all .5s",
    width: "100%",
    height: "81px",
    margin: "0",
    borderBottom: "1px rgba(255,255,255,.15) solid",
    boxShadow: "0 0 18px 0 rgb(0 0 0 / 12%)",
  },
  container: {
    width: "100%",
    minHeight: "100%",
    padding: "0",
    margin: "0",
    display: "flex",
    flexFlow: "row nowrap",
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  toolbar: {
    minHeight: "inherit",
    height: "81px",
    width: "100%",
    display: "flex",
    flexFlow: "row nowrap",
    alignContent: "center",
    justifyContent: { xs: "flex-end", md: "center" },
    alignItems: "center",
  },
  logo: {
    fontFamily: "monospace",
    fontWeight: 700,
    letterSpacing: ".3rem",
    color: "secondary.main",
    textDecoration: "none",
  },
  miniMenuBox: {
    position: "absolute",
    top: "15px",
    left: "15px",
  },
  mainBoxMenuButtons: {
    flexGrow: 3,
    display: "flex",
    flexFlow: "row nowrap",
    justifyContent: "center",
    minHeight: "inherit",
    height: "inherit",
    gap: "3%",
  },
  buttons: {
    my: 2,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  profileBox: {
    width: "81px",
    height: "81px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
};
