export const classes = {
  root: { position: "relative", height: "648px", color: "common.white" },
  shadow: {
    position: "absolute",
    width: "100%",
    left: "0",
    top: "0",
    height: "100%",
    opacity: ".7",
    backgroundColor: "#333",
  },
  mainContent: {
    position: "absolute",
    left: "50%",
    top: "50%",
    transform: "translate(-50%, -50%)",
    width: { xs: "85%", md: "74%" },
  },
  header: {
    color: "inherit",
    fontFamily: "nunito",
    fontSize: {
      sm: 40,
      xs: 30,
    },
    fontWeight: "bold",
    margin: { xs: "80px 0 0", md: "0 0 5px" },
  },
  secondHeader: {
    color: "common.white",
    opacity: ".7",
    margin: { xs: "0 0 100px", md: "0 0 50px" },
    fontSize: {
      sm: 24,
    },
    xs: 20,
    fontWeight: "light",
    lineHeight: "34px",
  },
  inputBase: { ml: 1, flex: 1, color: "inherit" },
  DefaultButton: {
    width: "145px",
    height: "60px",
    fontSize: "18px",
    margin: "0 5px 0 0",
    "&:hover": {
      backgroundColor: "background.main",
    },
  },
  paper: {
    margin: "0 auto 45px",
    p: "2px 4px",
    display: { xs: "none", md: "flex" },
    alignItems: "center",
    width: "100%",
    height: "76px",
    borderRadius: "50px",
    color: "primary.contrastText",
  },
  smallScreenSearch: {
    display: { xs: "flex", md: "none" },
    flexFlow: "column nowrap",
    alignContent: "center",
    alignItems: "flex-start",
    justifyContent: "center",
  },
  numbers: {
    color: "inherit",
    fontSize: 30,
    fontWeight: "light",
    lineHeight: "27px",
    margin: "0 0 3px 0",
  },
  numberNames: {
    color: "common.white",
    opacity: ".7",
    fontSize: 18,
  },
  list: {
    display: { xs: "none", md: "flex" },
    flexFlow: "row nowrap",
    height: "56px",
    padding: "0",
  },
  listItem: { width: "auto", minWidth: "fit-content", padding: 0 },
};
