export const classes = {
  root: {
    margin: "0 auto",
    padding: "65px 0 75px",
    alignItems: "center",
    borderBottom: "1px solid #e0e0e0",
  },
  top: {
    width: "80%",
    justifyContent: "space-between",
    margin: "0 auto 30px",
    flexFlow: { xs: "column", md: "row nowrap" },
  },
  header: {
    fontSize: 26,
    fontWeight: 500,
    color: "primary.dark",
    position: "relative",
    bgcolor: "unset",
    textTransform: "capitalize",
    margin: { xs: "0 0 40px", md: 0 },
    "&:before": {
      content: "''",
      position: "absolute",
      width: "50px",
      height: "2px",
      bottom: 0,
      bgcolor: "secondary.main",
    },
  },
  blogContainer: {
    width: "80%",
    alignContent: "center",
    justifyContent: "space-between",
    alignItems: "center",
    flexFlow: { xs: "column", lg: "row nowrap" },
    gap: "2%",
    color: "#fff",
  },
  blogItem: {
    flexBasis: { xs: "90%", lg: "32%" },
    margin: { xs: "0 0 30px 0", lg: 0 },
    transition: "all .3s",
    "&:hover": {
      "& .slideUp": {
        transform: "translate(0, 0)",
      },
      "& .showUp": {
        opacity: 0.8,
      },
    },
  },
  itemInnerContainer: {
    backgroundSize: "cover",
    backgroundPosition: "center",
    position: "relative",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
    width: "100%",
    minHeight: "450px",
  },
  shadowBox: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    opacity: 0.5,
    backgroundColor: "#333",
  },
  postTags: {
    position: "absolute",
    top: 30,
    left: 30,
    height: "26px",
    backgroundColor: "background.main",
    borderRadius: "4px",
    fontSize: "14px",
    color: "primary.main",
    padding: "3px 14px 5px",
  },
  para: {
    transition: "all .5s",
    color: "common.white",
    margin: "0 0 20px",
    opacity: 0,
  },
};
